name: Preparing to patch
runs:
  using: "composite"
  steps:
    - name: Set up jdk
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Install last jq version
      uses: vegardit/gha-setup-jq@v1
      with:
        use-cache: true
        version: 1.7.1
    - name: Install yq to handle toml
      uses: Makepad-fr/setup-yq-action@main
      with:
        version: '4.44.5'
    - name: Check if jq and yq are installed
      shell: bash
      run: |
        echo '::group::Check jq and yq installation'
        source ./src/etc/utils.sh        
        if command -v jq > /dev/null; then
          jqv=$(jq --version)
          blue_log "jq version installed: $jqv"
        else
          abort "jq is not installed"
        fi
        if command -v yq > /dev/null; then
          yqv=$(yq --version)
          blue_log "yq version installed: $yqv"
        else
          abort "yq is not installed"
        fi    
        
#    - name: Setup Cloudflare Warp
#      shell: bash
#      run: bash src/etc/cf_warp.sh
