name: Releasing APK files
description: Create a release with changelog

inputs:
  next_tag:
    description: 'Next tag for the release'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** (${{ inputs.next_tag }}) :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt

    - name: Create tag
      shell: bash
      run: |
        echo "Create tag: ${{ inputs.next_tag }}"
        echo "github.ref_name: ${{ github.ref_name }}"
        git tag -f ${{ inputs.next_tag }};git push -f origin ${{ inputs.next_tag }}
      
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: ./release/*.apk,./test-file.txt
        name: "Revanced & Revanced Extended"
        commit: main
        tag: 1
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
