name: Releasing APK files

inputs:
  next_tag:
    description: 'Next tag for the release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk,
          ./test-file.txt
        name: "Revanced & Revanced Extended"
        tag: ${{ inputs.next_tag }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
