name: Releasing APK files
description: Create a release with changelog

inputs:
  next_tag:
    description: 'Next tag for the release'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** (${{ inputs.next_tag }}) :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt

    - name: Set NEXT_TAG environment variable
      shell: bash
      run: echo "NEXT_TAG=${{ inputs.next_tag }}" >> $GITHUB_ENV
      
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: ./release/*.apk,./test-file.txt
        name: "Revanced & Revanced Extended"
        commit: main
        tag: ${{ env.NEXT_TAG }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
