name: Check Next Tag
description: Check if the next tag for the release has been retrieved and is valid
inputs:
  next_tag:
    description: 'Pass the next_tag variable'
    required: true
outputs:
  check_tag:
    description: 'Check if the next_tag variable is valid'
    value: ${{ steps.check_next_tag.outputs.check_tag }}
runs:
  using: "composite"
  steps:       
    - name: Check if setTag.sh exists
      shell: bash
      run: |
        echo '::group::Check if setTag.sh exists'
        SET_TAG_SCRIPT=./src/etc/setTag.sh
        if [ ! -f $SET_TAG_SCRIPT ]; then echo -e "::error::utils.sh [-] File not found: $SET_TAG_SCRIPT\n"; exit 1; fi

    - name: Make setTag.sh executable
      shell: bash
      run: |
        echo '::group::Make setTag.sh executable'
        chmod +x ./src/etc/setTag.sh

    - name: Check next tag
      id: check_next_tag
      shell: bash
      run: |
        echo '::group::Check next tag'
        ./src/etc/setTag.sh --check ${{ inputs.next_tag }}
