name: Set Next Tag
description: Get the next tag for the release
inputs:
  current-tag:
    description: 'Current tag for the release'
    required: false
    default: '0'
outputs:
  next_tag:
    description: 'Next tag for the release'
runs:
  using: "composite"
  env:
    SET_TAG_SCRIPT: ./src/etc/setTag.sh
        
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
  
    - name: Check if setTag.sh exists
      run: if [ ! -f $SET_TAG_SCRIPT ]; then echo -e "::error::utils.sh [-] File not found: $SET_TAG_SCRIPT\n"; exit 1; fi
  
    - name: Make setTag.sh executable
      run: chmod +x $SET_TAG_SCRIPT
  
    - name: Get next tag
      id: next_tag
      shell: bash
      run: $SET_TAG_SCRIPT ${{ inputs.current-tag }}

