name: Set Next Tag
description: Get the next tag for the release
inputs:
  current-tag:
    description: 'Current tag for the release'
    required: false
    default: '0'
outputs:
  next_tag:
    description: 'Next tag for the release'
runs:
  using: "composite"
  steps:
    - name: Get next tag
      id: next_tag
      shell: bash
      run: ./src/etc/setTag.sh ${{ inputs.current-tag }}
